### ISSUE TITLE
High CPU usage on bots

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/infrastructure#59]
Just got another one of those Linode high CPU usage mails (>90%).
That a bot server had very high CPU usage over the past couple hours.
There's no need to keep usage at a minimum, but it should be possible to keep usage consistently under 90%

/cc @DanVanAtta any ideas?

**Comment by RoiEXLab** [comment]
From the logs I couldn't find anything unusual apart from a lot of blocked requests.
Interestingly enough high CPU usage correlates with high IO Usage, so there might be a fundamental problem going on that makes the system proccess too much data at a time.

**Comment by DanVanAtta** [comment]
> so there might be a fundamental problem going on that makes the system proccess too much data at a time.

I would not be surprised at this. Bots were done very quickly out of an urgent need, and there was not a ton of development effort following their release. I think it's best if we focus on cleaning that code and reducing dependencies on game data. I suspect going that route we would fix this problem without realizing it; But otherwise there is something going on it seems..

**Comment by prastle** [comment]
@RoiEXLab  @DanVanAtta  Since we have a new bot hoster and hopefully a second one coming online this week.  (Roi could answer about the second one better) Maybe we should reduce all the bot servers to three bots per server?  Would that solve the hi mem usage?  Or possibly remove one server as well?

**Comment by RoiEXLab** [comment]
I'd need to fix the scripts to allow for a downgrade, but other than that that should be possible

**Comment by RoiEXLab** [comment]
#60

**Comment by prastle** [comment]
If we just stop the 4rth bot does that not accomplish the goal?  Or will it restart from stopped?  @RoiEXLab

**Comment by RoiEXLab** [comment]
We'd disable them remotely from github. 
Otherwise they'd just restart due to the same problem we had with the fifth bot

**Comment by prastle** [comment]
KK I remote stopped 104 ill watch to see if it relaunches

**Comment by RoiEXLab** [comment]
@prastle It won't, but it will restart when the server restarts.

**Comment by prastle** [comment]
Nope relaunched with putty stop and toolbox either way you are cor they will relaunch.

**Comment by DanVanAtta** [comment]
> Maybe we should reduce all the bot servers to three bots per server? Would that solve the hi mem usage? Or possibly remove one server as well?

In short, no. The problem is that the code uses a ton of memory to load maps, and then while the game is running there are likely memory leaks that cause more memory to become wasted and used.

Going from 3->4 will allow for there to be more memory on the system, but we could get the same effect by reducing the amount of memory per bot. If we go with 3, we can increase the amount of memory per bot. As is, they have more memory allocated than they should really need. 

> Or possibly remove one server as well?

In general I would encourage us to *not* muck with the bots, the effort of communicating these plans and making the code changes hardly seems worth it; our time is 10,000x more valuable than the cost of a bot server. But ultimately the fixes seem to be with the code. IF we go with 3 bots with more memory, they'll leak/use available memory and it should not be any better. IF the lack of free memory on systems is a problem the first thing to do would be to reduce the memory per bot, and if that goes below a minimum needed to run a bot then going to 3 would be appropriate.

**Comment by DanVanAtta** [comment]
@RoiEXLab the bot count went from 4 to 3, it seems to me any high cpu usage issues beyond that are not deployment related but application problems instead. Would you agree? Is there something we can fix on the deployment side? Is there a problem on the deploymetn side?

**Comment by prastle** [comment]
The simple answer is YES we can add more bot servers if they are fixable.  Sadly as mentioned elsewhere many of the servers can't be stopped permanently when they run too many bots.  @Roi attempted to drop them to three each but infra is still launching 4 at times and under one or 2 on others.  The first step is fixing the ssh fgor all server admins so any of us can fix them.  Since it is only Roi an d myself and you that seem to be able to do this.  This was attempted before infra changes.  Either way simple truth is even on the bot servers we can stop they restart themselves anyways.  The good news is that the ones I did yesterday seem to have remained in operation.  To the best of my knowledge no one except you @DanVanAtta  can do anything with jp.

**Comment by RoiEXLab** [comment]
As @prastle Already mentioned I tried allowing simple downgrades a while back which didn't seem to work.
This would need further investigation to find the root cause for this.
I haven't tried doing something with jp yet,  because the simple truth is I don't have the time for it.
When I have some time during the weekend, this time is being spent fixing potentially release blocking bugs or cleaning up code I noticed while fixing bugs. And then the weekend is already over.

**Comment by DanVanAtta** [comment]
'yes' to which question? 

I've yet to see the evidence the high CPU is due to having too many bots and not instead the application consuming a burst of CPU usage. 

This is also not the ticket to track whether downgrading from 4 bots to 3 works. That was not originally supported. We might be there now with recent fixes.

*****

With 3 bots configured, if that actually works in terms of deployment is not up to this ticket. I also am unsure of the evidence that a high CPU alarm is not due to a burst of CPU usage by one of the bot instances. If 4 bots were the probelm, then why don't we see this problem nearly all the time? Going to 3 bots would help relieve that pressure, but it does seem like the fix is actually somewhere else until we understand why/when we get the high CPU alarms (I suspect the fix is going to be with the application code).

**Comment by prastle** [comment]
I can actually answer your above ? quite easily.  @DanVanAtta  they crash and lock up when a long running game with many observers occurs on multiplr bots of the same server.

**Comment by prastle** [comment]
If the game gets reloaded it does not happen unless 3 or 4 games similar at once or a few really heavy maps being run... Example WAW and TWW x4 on same server with many players

**Comment by prastle** [comment]
Thus three bots per server will help alleviate this until the mem leak? is found.  I agree that theoretically this shouldn't matter but sadly that is not the case.

**Comment by DanVanAtta** [comment]
@prastle a memory leak will chew up memory regardless of how many bot instances are running. That is not necessarily related to CPU. Seems like for this ticket we need to identify CPU usage issues. Let's re-open or track any production problems in the main triplea-game issue queue so we can keep things in one place.
